/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:66ba629e-6705-40f0-b3a1-c67e56c70106",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_jYM9I9ohK",
    "aws_user_pools_web_client_id": "606b7bbudq0oocrspm4ad7lcka",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ttbstorage235824-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_content_delivery_bucket": "www.teachertoolbox.net-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://d3bdkq4wu9sxmk.cloudfront.net"
};


export default awsmobile;
